bazel: fix for bazel 6.0.0
bazel 6.0.0 introduced a change which is backward incompatible, see:
https://github.com/bazelbuild/bazel/issues/8622

The upb package (@upb) which is a dependancy for rules_proto_grpc
(@rules_proto_grpc) had lines in its build which were targeting
@bazel_tools//platforms:windows, which had been removed.
This made it impossible to build on bazel 6.0.0.
Update the rules_proto_grpc to 4.3.0 to resolve this.

Building with the updated version of rules_proto_grpc
would then fail because @com_github_grpc_grpc required c++14 in lots
of files. Example error:
external/com_github_grpc_grpc/src/core/lib/gpr/useful.h:109:17: error:
use of 'auto' in lambda parameter declaration only available with
'-std=c++14' or '-std=gnu++14'

Add a .bazelrc file to force c++14 when building.

Also bump the version of the com_google_googleapis package.